kind: Deployment
apiVersion: apps/v1
metadata:  
  name: nginx
  #deployment labels
  labels:
    app: nginx
    tier: frontend
    purpose: deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deployment
  template: 
    metadata:
     labels:
       app: nginx
       tier: frontend
       purpose: deployment
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}
        ports:
        - containerPort: 80   
